#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export DOTFILES=$HOME/.dotfiles

# reload zsh config
alias reload!='source ~/.zshrc'

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Source functions.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/functions.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/functions.zsh"
fi

# Base16 Shell
if [ -z "$THEME" ]; then
    export THEME="base16-atelierheath"
fi
if [ -z "$BACKGROUND" ]; then
    export BACKGROUND="dark"
fi

BASE16_SHELL="$DOTFILES/.config/base16-shell/$THEME.$BACKGROUND.sh"
# [[ -s $BASE16_SHELL ]] && source $BASE16_SHELL
source $BASE16_SHELL